### ISSUE TITLE
Several Build & Launch issues on Windows & Linux

### ISSUE THREAD

**Issue by LaylDupont** [vgc/vgc#16]
De nombreux problèmes lors du build et du lancement de l'application pour parvenir à avoir un petit aperçu du logiciel !

1# Sous linux, compilé avec Clang: Erreur de build dûe à un nom de fonction identique à Qt et à une ambigüité du namespace ( la fonction setWindowFlag dans colordialog.cpp )
Pour résoudre:
file: colordialog.cpp line: 55
La ligne:
> setWindowFlag(this, Qt::WindowMinimizeButtonHint, false);
Devient:
< ::setWindowFlag(this, Qt::WindowMinimizeButtonHint, false);

2# Sous Linux, compilé avec Clang: Une fois l'application compilée ( + après double check de la version de Qt ainsi que de Python ), l'application démarre mais le système crash systématiquement !

3# Sous Windows, erreur suspecte émise par CMake:
"You have called ADD_LIBRARY for library vgc_lib_opengl without any source files. This typically indicates a problem with your CMakeLists.txt file"
Est-ce normal ? Je n'ai pas creusé plus loin, voir problèmes suivants.

4# Sous Windows, le projet généré par CMake ne compîle pas, il n'inclut pas les bonnes dépendances vers OpenGL ( OpenGL32.lib ) ( testé avec le générateur pour Visual Studio 2017 ), est-ce lié avec l'erreur émise par CMake lors de la génération du projet ?

5# Sous Windows, le projet généré par CMake ne compile pas, les fonctions
< double near() const { return near_; }
< double far() const { return far_; }
du fichier camera2d.cpp
soulèvent une erreur de syntaxe car il existe sous Windows un define pour les termes near & far.
Problème temporairement résolu avec ces deux lignes au début du fichier camera2d.h:
> #undef near
> #undef far

6# Sous Windows, compilé avec avec MSVC 2017:
La DLL vgcopengl.dll n'exporte aucun symbole ( vérifié avec DUMPBIN /exports sous windows ) mais ne cause pas de problèmes.
La DLL vgcdom.dll cause une errreur lors du chargement des dépendances externes dynamiques ( erreur 0xc000007b ), elle exporte pourtant bien un certain nombre de symboles qui ont l'air cohérents.

**Comment by dalboris** [comment]
Merci beaucoup pour tous ces retours ! Je ne travaille pour l'instant que 
sur Linux et compile avec gcc, donc ce genre d'erreurs avec d'autres 
compilateurs ou plateformes ne me surprennent pas.

Je peux essayer de résoudre ces problèmes au plus vite cependant.

**Comment by dalboris** [comment]
Update: I just started to attempt a compilation on Windows, I report here how it goes.

I have the following config:
- Windows 7 Pro 64-bit
- [Python 3.6.6 64-bit](https://www.python.org/ftp/python/3.6.6/python-3.6.6-amd64-webinstall.exe)
- [Visual Studio Community 2015](https://visualstudio.microsoft.com/vs/older-downloads/)
- [Qt 5.6.3 for msvc2015 64-bit](https://www.qt.io/download-thank-you?os=windows)
- [CMake 3.12.2](https://cmake.org/files/v3.12/cmake-3.12.2-win64-x64.msi)

After installing all the above, I can run cmake successfully in cmd.exe via the following:
```
git clone https://github.com/vgc/vgc.git
mkdir build-vgc
cd build-vgc
cmake ../vgc -G "Visual Studio 14 2015 Win64" -DQt5_DIR="C:\Qt\5.6.3\msvc2015_64\lib\cmake\Qt5"
```

This generates a file `ALL_BUILD.vcxproj`, which I open on VS 2015, and do Build > Build Solution (Ctrl+Shift+B).

There are tons of errors and warnings. Note that 1# is already fixed (see #30 ). 3# shouldn't be a problem: there is indeed no symbols yet in vgcopengl.dll, this modules is only here to provide two resource files for now (a very basic shader), but soon will also hosts useful opengl functions. I'm not sure about 4#. I'll fix 5# very shortly. 

Most other errors/warnings seem to be caused by symbols not properly exported in the DLLs, which is likely the cause of the crashes you're having (2#, 6#). These will be non-trivial to fix. The main issue seems to be that I'm passing STL classes across DLL boundaries, or exporting classes that derive from non-exported STL classes (e.g., std::runtime_error, std::logic_error, std::enable_shared_from_this).

I didn't have to deal with any of this in VPaint because I was compiling everything statically. Unfortunately, in VGC, I'm using shared libraries in order to be able to provide python bindings (I don't think it's possible using static libraries), but I don't have much expertise yet in doing so. I'll have to learn what's the best course of action is, some possibilities are the following:
- Ignore the warnings and assume everything is always compiled with the same version of the STL.
- Don't use the STL.
- Use the PIMPL idiom to hide the STL.

Related:
- https://stackoverflow.com/questions/767579/exporting-classes-containing-std-objects-vector-map-etc-from-a-dll
- https://stackoverflow.com/questions/4145605/stdvector-needs-to-have-dll-interface-to-be-used-by-clients-of-class-xt-war
- https://stackoverflow.com/questions/8301747/export-parent-class-without-base-class-in-c
- https://social.msdn.microsoft.com/Forums/vstudio/en-US/df99b712-c00b-4af0-82fd-3764c8b6cbec/exporting-stdstring-from-a-dll-does-not-export-stdstringnpos?forum=vcgeneral
- https://lists.boost.org/boost-users/2011/09/70889.php
- https://stackoverflow.com/questions/5661738/how-can-i-use-standard-library-stl-classes-in-my-dll-interface-or-abi

**Comment by dalboris** [comment]
Note: 5# is now fixed with your suggested change. See #31.

**Comment by dalboris** [comment]
Ok, I finally managed to get VGC running on Windows 7!! :)

![vgc_on_windows_7](https://user-images.githubusercontent.com/4809739/45710563-42c53680-bb87-11e8-8b81-15a122189c7b.jpg)

Here is the exact config:
- Windows 7 Pro 64-bit
- Python 3.6.6 64-bit
- Visual Studio Community 2017
- Qt 5.11.1 for MSVC 2017 64-bit
- CMake 3.12.2

I did the following in cmd.exe:
```
git clone https://github.com/vgc/vgc.git
mkdir build-vgc
cd build-vgc
cmake ../vgc -G "Visual Studio 15 2017 Win64" -DQt5_DIR="C:\Qt\5.11.1\msvc2017_64\lib\cmake\Qt5"
```

Then I opened build-vgc\vgc.sln in Visual Studio 2017. I built the solution (Ctrl+Shift+B), it is a Debug build by default. It compiled but failed to run from VS. To be able to run the compiled binary, I copied all the relevant dlls to build-vgc\bin\Debug\, then simply double-clicked on build-vgc\bin\Debug\vgcillustration.exe in the file explorer. 

The minimal set of dlls to copy was:
- C:\Qt\5.11.1\msvc2017_64\bin\Qt5Cored.dll
- C:\Qt\5.11.1\msvc2017_64\bin\Qt5Guid.dll
- C:\Qt\5.11.1\msvc2017_64\bin\Qt5Widgetsd.dll
- build-vgc\libs\vgc\core\Debug\vgccore.dll
- build-vgc\libs\vgc\dom\Debug\vgcdom.dll
- build-vgc\libs\vgc\geometry\Debug\vgcgeometry.dll
- build-vgc\libs\vgc\widgets\Debug\vgcwidget.dll

Similar steps work for a Release build, by specifying "Release" in Visual Studio, building the project, then copying the following relevant dlls to  build-vgc\bin\Release:
- C:\Qt\5.11.1\msvc2017_64\bin\Qt5Core.dll
- C:\Qt\5.11.1\msvc2017_64\bin\Qt5Gui.dll
- C:\Qt\5.11.1\msvc2017_64\bin\Qt5Widgets.dll
- build-vgc\libs\vgc\core\Release\vgccore.dll
- build-vgc\libs\vgc\dom\Release\vgcdom.dll
- build-vgc\libs\vgc\geometry\Release\vgcgeometry.dll
- build-vgc\libs\vgc\widgets\Release\vgcwidget.dll
