### ISSUE TITLE
Fail to compile on linux.

### ISSUE THREAD

**Issue by ebarranco** [vgc/vgc#30]
Hi, I tried to compile in Manjaro linux 64bit and everything seems right until  87% 
Can you point it out my problem here?
![screenshot_20180911_151101](https://user-images.githubusercontent.com/11136544/45385017-5693fa00-b5d5-11e8-9036-37eddde04689.png)

**Comment by dalboris** [comment]
Hi @ebarranco, thanks for reporting!

The bug should be fix, can you do `git pull`, then `make` again, and see if it works now?

The problem seems that you are using Qt 5.9+, while I am using Qt 5.6 (which is the targeted version for now). When using Qt 5.9+, the function `QWidget::setWindowFlag()` (introduced in Qt 5.9) is being called, instead of our own function `setWindowFlag` defined in `vgc/widgets/colordialog.cpp`. To disambiguate, we should either:
1. Call `::setWindowFlag`,
2. Change the name to something else (e.g., `setWindowFlag_`), or
3. Use preprocessor macros to call `QWidget::setWindowFlag()` when using Qt5.9+

I chose #2.

**Comment by ebarranco** [comment]
I wrongly assumed that the qt version that you wrote in the instructions it was the latest one. I updated my sources and I can build and execute vgc illustration now. My tablet works perfectly, I drew and changed colours, I was able to save and open my drawing file without problem. Thank you.

**Comment by dalboris** [comment]
Awesome, I'm glad you could compile and that it works!

Be aware that you may currently see some lag when drawing when the number of strokes become large (say, 1000+), as rendering is not yet very optimized. I'd like to improve this before the alpha version, so that people can test it to the limit and check that there is no lag ;)

**Comment by ebarranco** [comment]
Ok, I'll be follow closely the development and let you know any issue I found.
