### ISSUE TITLE
Hardcoded compile-time paths

### ISSUE THREAD

**Issue by probonopd** [vgc/vgc#51]
I am trying to build an [AppImage](https://appimage.org/) of vgc.

This is the `.travis.yml` I use:
https://github.com/probonopd/vgc/blob/9a26c8c49ff834e49a341c6d319edea6500cc844/.travis.yml

This is the AppImage:
https://github.com/probonopd/vgc/releases

The application runs with the following errors:

```
me@host:~$ Downloads/VGC-7df6e61-x86_64.AppImage 
QOpenGLShader: Unable to open file "/home/travis/build/probonopd/vgc/build/resources/opengl/shaders/shader.v.glsl"
QOpenGLShader: Unable to open file "/home/travis/build/probonopd/vgc/build/resources/opengl/shaders/shader.f.glsl"
QOpenGLShader::link: error: no shaders attached to the program

QOpenGLShader::link: error: no shaders attached to the program

QOpenGLShaderProgram::attributeLocation(vertex): shader program is not linked
QOpenGLShaderProgram::uniformLocation(projMatrix): shader program is not linked
QOpenGLShaderProgram::uniformLocation(viewMatrix): shader program is not linked
QOpenGLShaderProgram::uniformLocation(color): shader program is not linked
QOpenGLShader::link: error: no shaders attached to the program
```
`/home/travis/build/probonopd/vgc/build/` is a build-time path from Travis CI that should not be used in the final compiled application. Instead, the application should retrieve its resources from paths relative to itself, e.g., using `QString QCoreApplication::applicationDirPath()`.

**Comment by dalboris** [comment]
By the way, I absolutely love your `$(git rev-parse --short HEAD)`. It is a great idea to add it to the AppImage name, and in fact, I was thinking about doing the same in the CMakeLists to define a C++ macro so the app itself knows its git commit hash and can display it in its Help > About dialog.

**Comment by dalboris** [comment]
I just looked at your profile, sorry, my first question was silly :-P Thanks a lot for the help, your experience is very appreciated!

**Comment by probonopd** [comment]
You could fall back to using the `$APPDIR` environment variable. For this to work even in unpacked AppImages (=AppDirs), you should export this variable in a custom `AppRun` launcher script like so:

```
#!/bin/sh
SELF=$(readlink -f "$0")
export APPDIR=${SELF%/*}
exec ... "$@"
```

> Should each app be its own AppImage, and have its own copy of all VGC libraries?

If the two applications are both used independently, make two AppImages. If the two are mainly used in conjunction and one is the main application, just make one AppImage for the main application and allow for the auxiliary application to be launched through a symlink, along the lines of https://github.com/ImageMagick/ImageMagick/blob/bc8825e12f58d6f34003b849c0d331732cd5c8b9/AppRun.

**Comment by dalboris** [comment]
By using $APPDIR would never work when using the python bindings, right? Example session:

```
$ python
>>> from vgc.opengl import drawStuff
>>> vgc.opengl.drawStuff()
```

Where `drawStuff` depends on `resouces/opengl/shaders/shader.f.glsl`, for example.

**Comment by probonopd** [comment]
Frankly, I don't know how your software works. Never heard of `glsl` files. Think of AppImage as a self-mounting filesystem that executes whatever you put inside it. Like a zip or an ISO. I don't know what goes on inside. All I can say is that complex Python based applications like [Ultimaker Cura](https://ultimaker.com/en/products/ultimaker-cura-software) are distributed in AppImage form, by bundling a private copy of Python and all of its modules that are needed. Possibly https://github.com/linuxdeploy/linuxdeploy-plugin-conda can be useful here.

**Comment by dalboris** [comment]
Thanks for your answer, and yes, shipping Python inside the AppImage is probably best.

However, my question was more generic: just imagine any C++ shared library (the 'library') that depends on some external non-C++ file loaded at run-time (the 'resource'). There are invariants between the library and the resource, so the resource should not be user-provided. Where should the resource live, and how should the library know where the resource live?

In the case of using the library for an application deployed as an AppImage, it's easy: each application has its own AppImage with its own copy of the library, and everything can indeed be relative to the application path. But using AppImages is just one possible deployment method, what if instead the library is installed system-wide, and two different applications use this shared library? Since these applications may not live at the same path, locating the resource relative to the application path makes no sense.

Any insight on how this case is typically dealt with, so that the library can be easily deployed as part of an AppImage, but also as a standalone shared library installed system-wide, and used by different applications?

**Comment by dalboris** [comment]
Yes, this is exactly what I meant, and the problem was indeed how to get `$ORIGIN` from C++. Thanks for the additional info, and the other locations where resources might possibly be installed.

For now, I have decided to simply require clients to tell the library where its resources are located. This makes it explicit and robust to any installation method, at the cost of a minor inconvenience when using the library. I may add automatic detection in the future via binreloc, but it's low priority.

I have managed to create a working AppImage locally, and I'm now in the process of providing a `cmake appimages` command so that deploying as AppImages is straightforward. You can follow this work here if you wish: #58 

I'm closing this specific issue since there should be no built-in compile paths now.

And by the way: thanks a lot for your work on AppImage and linuxdeplyqt, those are quite amazing tools! :)
